name: Test Workflow
on:
  push:
  schedule:
    - cron: '0 6 * * *'
jobs:
  # Checkout in separate job because docker image is alpine based and checkout action doesn't work.
  #checkout_build:
  #  runs-on: ubuntu-latest
  #  container:
  #    image: quay.io/pantheon-public/php-ci:v7.4
  #  name: Checkout & build Phar
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v3
  #    - name: Save repo content as artifact
  #      uses: actions/upload-artifact@v3
  #      with:
  #        name: full-workspace
  #        path: ${{ github.workspace }}

  functional:
    runs-on: ${{ matrix.operating-system }}
    name: Functional testing matrix - PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    #if: ${{ github.repository_owner == 'pantheon-systems' }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest', 'macos-latest' ]
        php-versions: [ '7.4', '8.0', '8.1' ]
      max-parallel: 5
    #needs: [ checkout_build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, mbstring, zip, ssh2-1.3.1
          coverage: pcov
          ini-values: error_reporting=E_ALL
      #- name: Download repo content from artifact
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: full-workspace
      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Functional Tests
        run: composer test
